# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import co_sim_pb2 as co__sim__pb2


class CoSimStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RMVal = channel.unary_unary(
                '/cosim.CoSim/RMVal',
                request_serializer=co__sim__pb2.SimPayload.SerializeToString,
                response_deserializer=co__sim__pb2.SimPayload.FromString,
                )


class CoSimServicer(object):
    """Missing associated documentation comment in .proto file"""

    def RMVal(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RMVal': grpc.unary_unary_rpc_method_handler(
                    servicer.RMVal,
                    request_deserializer=co__sim__pb2.SimPayload.FromString,
                    response_serializer=co__sim__pb2.SimPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosim.CoSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoSim(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def RMVal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cosim.CoSim/RMVal',
            co__sim__pb2.SimPayload.SerializeToString,
            co__sim__pb2.SimPayload.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
