# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: co_sim.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='co_sim.proto',
  package='cosim',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x63o_sim.proto\x12\x05\x63osim\"<\n\nSimPayload\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63hannels\x18\x02 \x03(\t\x12\x0e\n\x06\x62uffer\x18\x03 \x03(\x05\x32\x38\n\x05\x43oSim\x12/\n\x05RMVal\x12\x11.cosim.SimPayload\x1a\x11.cosim.SimPayload\"\x00\x62\x06proto3'
)




_SIMPAYLOAD = _descriptor.Descriptor(
  name='SimPayload',
  full_name='cosim.SimPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cosim.SimPayload.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='cosim.SimPayload.channels', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='cosim.SimPayload.buffer', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['SimPayload'] = _SIMPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimPayload = _reflection.GeneratedProtocolMessageType('SimPayload', (_message.Message,), {
  'DESCRIPTOR' : _SIMPAYLOAD,
  '__module__' : 'co_sim_pb2'
  # @@protoc_insertion_point(class_scope:cosim.SimPayload)
  })
_sym_db.RegisterMessage(SimPayload)



_COSIM = _descriptor.ServiceDescriptor(
  name='CoSim',
  full_name='cosim.CoSim',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=85,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='RMVal',
    full_name='cosim.CoSim.RMVal',
    index=0,
    containing_service=None,
    input_type=_SIMPAYLOAD,
    output_type=_SIMPAYLOAD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COSIM)

DESCRIPTOR.services_by_name['CoSim'] = _COSIM

# @@protoc_insertion_point(module_scope)
